language: node_js
node_js:
  - "6.1"
script: "npm run lint-and-test"

notifications:
  slack:
    rooms:
      - moveonorg:OTFzZVGzKuhTSw5daB5MjHiL#mop-tech
    on_success: always
    on_failure: always
    on_start: never
